cache:
   pipeline: ["~/.m2"]

annotations:
   screwdriver.cd/restrictPR: fork

shared:
   annotations:
       screwdriver.cd/cpu: TURBO
       screwdriver.cd/ram: TURBO

   environment:
       #Fetches history so Sonar can assign blame.
       GIT_SHALLOW_CLONE: false

jobs:
  master-commit:
    image: maven:3.8.2-openjdk-11
    requires: [~pr, ~commit]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-7-build:
    image: maven:3.8.5-openjdk-17
    requires: [~pr:elide-7.x, ~commit:elide-7.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-6-build:
    image: maven:3.8.2-openjdk-11
    requires: [~pr:elide-6.x, ~commit:elide-6.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-5-build:
    image: maven:3.6.3-jdk-8
    requires: [~pr:elide-5.x, ~commit:elide-5.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-4-build:
    image: maven:3.6.3-jdk-8
    requires: [~pr:elide-4.x, ~commit:elide-4.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  release-java17:
    image: maven:3.8.5-openjdk-17
    secrets:
        - GPG_KEYNAME
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER
        - OSSRH_TOKEN
    requires: [~tag:/^7/, ~release:/^7/]
    steps:
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"

  release-java11:
    image: maven:3.8.2-openjdk-11
    secrets:
        - GPG_KEYNAME
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER
        - OSSRH_TOKEN
    requires: [~tag:/^6/, ~release:/^6/]
    steps:
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"

