cache:
   pipeline: ["~/.m2"]

annotations:
   screwdriver.cd/restrictPR: fork

shared:
   annotations:
       screwdriver.cd/cpu: TURBO
       screwdriver.cd/ram: TURBO
   image: maven:3.6.3-jdk-8
   environment:
       #Fetches history so Sonar can assign blame.
       GIT_SHALLOW_CLONE: false

jobs:
  master-commit:
    image: maven:3.8.2-openjdk-11
    requires: [~pr, ~commit]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-6-build:
    image: maven:3.8.2-openjdk-11
    requires: [~pr:elide-6.x, ~commit:elide-6.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-5-build:
    requires: [~pr:elide-5.x, ~commit:elide-5.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  elide-4-build:
    requires: [~pr:elide-4.x, ~commit:elide-4.x]
    secrets:
        - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean verify coveralls:report

  release:
    secrets:
        - GPG_KEYNAME
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER
        - OSSRH_TOKEN
    requires: [~tag, ~release]
    steps:
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"

