package graphql.java.generator.type.reflect;

import graphql.java.generator.type.strategies.TypeDescriptionStrategy;

public class TypeDescription_ReflectionAutogen implements TypeDescriptionStrategy {

    @Override
    public String getTypeDescription(Object object) {
        Class<?> clazz = ReflectionUtils.extractClassFromSupportedObject(object);
        if (clazz == null) return null;
        return "Autogenerated for j.l.Class: " + clazz.getCanonicalName();
    }
}
