package graphql.java.generator.field.reflect;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

import graphql.java.generator.field.strategies.FieldDescriptionStrategy;

public class FieldDescription_ReflectionAutogen implements FieldDescriptionStrategy {
    
    @Override
    public String getFieldDescription(Object object) {
        if (object instanceof Field) {
            return getFieldDescriptionFromField((Field)object);
        }
        if (object instanceof Method) {
            return getFieldDescriptionFromMethod((Method)object);
        }
        return null;
    }

    protected String getFieldDescriptionFromMethod(Method method) {
        return "Autogenerated from j.l.r.Method [" + method.toGenericString() + "]";
    }

    protected String getFieldDescriptionFromField(Field field) {
        return "Autogenerated from j.l.r.Field [" + field.toGenericString() + "]";
    }
}
